name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      who-to-greet:
        description: 'Person Greeting'
        type: string
        required: true
        default: world
    outputs: 
      curent-time:
        description: 'time when greeting'
        value: ${{jobs.reusable-job.outputs.current-time}}
jobs:
  reusable-job: 
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{steps.time.outputs.time}}
    steps:
    - name: Greet Somepone 
      run: echo "hello ${{inputs.who-to-greet}}"
    - name: set time
      id: time
      run: echo "time = $(date)" >> $GITHUB_OUTPUT
    
        
        
